from backend.api.v1.routers import (
    transacciones,
    presupuestos,
    obligaciones,
    inversiones,
    catalogos,
    inbox,
    reglas,
    reportes,
    analitica,
    backup,
    dashboard,
    tools,
    pwa_config,
)

__all__ = [
    "transacciones",
    "presupuestos",
    "obligaciones",
    "inversiones",
    "catalogos",
    "inbox",
    "reglas",
    "reportes",
    "analitica",
    "backup",
    "dashboard",
    "tools",
    "pwa_config",
]
